name: Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python main.py